### ISSUE TITLE
Broken styles for copy button

### ISSUE THREAD

**Issue by AhsanAyaz** [IOMechs/pure-css-loaders-extended#65] opened 2021-10-29 12:39 UTC
The text Copy is not centered

![image](https://user-images.githubusercontent.com/9844254/139435801-e0851405-51e2-48ff-8b85-141fe9f6cb61.png)

**Comment by zuhairnaqi** [comment] 2021-10-30 15:31
I can't reproduce this issue on the main branch

**Comment by taimooralqureshi** [comment] 2021-11-14 22:07
this Issue is closing by #69

**Closed** 2021-11-18 10:20 UTC
